# Generated by Django 5.1.1 on 2024-09-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='media/article_attachments/files')),
                ('image_attachment', models.ImageField(blank=True, null=True, upload_to='media/article_attachments/images')),
                ('content', models.TextField()),
                ('user_name', models.TextField(max_length=120)),
                ('title', models.TextField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('write_article', 'Writes article')],
            },
        ),
    ]
