# Generated by Django 5.1.1 on 2024-09-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='media/tickets_attachments')),
                ('content', models.TextField(max_length=1200)),
                ('title', models.TextField(max_length=60)),
                ('user_name', models.TextField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('status_ticket', 'Changes ticket status')],
            },
        ),
    ]
