# Generated by Django 5.1.1 on 2024-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('inprogress', 'In progress'), ('closed', 'Closed')], max_length=30),
        ),
    ]
