# Generated by Django 5.1.1 on 2025-03-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='responsible',
        ),
    ]
