# Generated by Django 5.1.1 on 2024-09-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='media/ticket_attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_ticket', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create_ticket', 'allows to create tickets'), ('delete_tickets', 'allows to delete tickets'), ('modify_tickets', 'allows to modify tickets')],
            },
        ),
    ]
