# Generated by Django 5.1.1 on 2024-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(default='operator', max_length=30),
            preserve_default=False,
        ),
    ]
